### ISSUE TITLE
Unable to make connection with ArduinoPOCServer.exe

### ISSUE THREAD

**Issue by OptifySudarshanPatil** [SoftwareTools4Makers/OPC#11]
Every time in process of adding server in dOPC, ArduinoPOCServer.exe get crashed and unable to established connection.

**Comment by ildemartinez** [comment]
did you started exe file with Admin rights? do you have installed the opc library framework?

**Comment by aminhusni** [comment]
Somewhat of the same issue. 
ArduinoOPCServer does not appear on the Local Machine section in KEPServerEX 6. 
The Arduino OPC Server was run in administrator mode. 

Update: Fixed it by running register.bat as administrator.
