### ISSUE TITLE
License

### ISSUE THREAD

**Issue by bangonkali** [SoftwareTools4Makers/OPC#2]
This is an awesome work! I just recently bought the [Lolin NodeMCU V3 Board](https://www.youtube.com/watch?v=weLO8kjhzeA) which has an on-board WiFi and quite a small footprint. I was wondering if I could port this project to that board. What is your plan so far as to the License of the Source Code? Can I freely port it to other board and sell the board? Personally I don't mind sharing the ported source code.

**Comment by ildemartinez** [comment]
Hello

sorry.... I havent saw the message before....How is your project going?

all the best
ilde

**Comment by bangonkali** [comment]
I have not tried your code yet. But I'm very interested in checking it out. Have you guys decided on the license?
