### ISSUE TITLE
OPC for ESP8266

### ISSUE THREAD

**Issue by ProximaB** [SoftwareTools4Makers/OPC#5]
Hi,
I want to expand your OPC library with ESP8266 support. I finally set up everything and understand library code and will write core connection in this week. 22/05/18

**Comment by ProximaB** [comment]
@ildemartinez  Could you check issue tab at https://github.com/ProximaB/OPC

**Comment by carlostorrez** [comment]
Ya tienes algun avance del OPC para el ESP8266?

**Comment by ProximaB** [comment]
Yes, it works check the link  https://github.com/ProximaB/OPC 
1. Download OPC for Arduino from http://www.st4makers.com/ and open it with admin privileges.
2. Upload NodeMCU example to your Esp8266. Notice that you need to edit ssid and password of WiFi before).
3. Check what is the IP of Esp8266, you can use serial to obtain it.
4. In the OPC for Arduino add Ethernet and type I and port of your esp, save it.
5. Test if its working with eg. Kassl dOPC Explorer.Tip: This explorer works only if you put it in : C:\Program Files\Kassl\

**Comment by ildemartinez** [comment]
Sorry for the delay!!! great work!!!

**Comment by debashisiitbt** [comment]
The OPC Master library in this link https://github.com/ProximaB/OPC has the file NodeMcu Example Sketch but not having the command for connecting the NodeMcu to Wifi or provision for setting up the ssid and password or IP.

**Comment by debashisiitbt** [comment]
> Yes, it works check the link https://github.com/ProximaB/OPC
> 
> 1. Download OPC for Arduino from http://www.st4makers.com/ and open it with admin privileges.
> 2. Upload NodeMCU example to your Esp8266. Notice that you need to edit ssid and password of WiFi before).
> 3. Check what is the IP of Esp8266, you can use serial to obtain it.
> 4. In the OPC for Arduino add Ethernet and type I and port of your esp, save it.
> 5. Test if its working with eg. Kassl dOPC Explorer.Tip: This explorer works only if you put it in : C:\Program Files\Kassl\
The OPC Master library in this link https://github.com/ProximaB/OPC has the file NodeMcu Example Sketch but not having the command for connecting the NodeMcu to Wifi or provision for setting up the ssid and password or IP.

**Comment by ProximaB** [comment]
@debashisiitbt check out this line of code 	myNodeMcu.setup("Internet_57", "123456789", 80);

**Comment by debashisiitbt** [comment]
Dear ProximaB

Thanks a lot for your support but still I am facing a problem in compiling the sketch for NodeMcu board it is giving a message during compiling.

exit status 1
'OPCNodeMcu" does not name a type

**Comment by ruk-shan** [comment]
> 'OPCNodeMcu" does not name a type

i have the same issue... Any solutions.

**Comment by ProximaB** [comment]
> > 'OPCNodeMcu" does not name a type
> 
> i have the same issue... Any solutions.

I suppose that It doesn't linking proper OPC source files.
I'm not able to compile the code and run it but just for testing purposes and because opc is small library try following steps.
Copy OPC.ino and OPC.h to your current working directory and use it directly.

At that time I was using visualMicro for Visual Studio, it was great but I think it's not necessarily good thing to depends on that.

If you would like to help please fork my repo and clean that out. Thanks 😊

**Comment by ruk-shan** [comment]
Thank you very much. I managed to compile it and upload it to my esp8266. 
It connects to wifi network and my Linux pc able to ping it. However when i try with UAExpert to connect, it fails to connect. (I changed the port to 4840). Am I missing something here?
